### PR TITLE
Master

### PR DESCRIPTION
**Pull request by KaiSchu**
Hi,

exciting news! The Lid-driven cavity problem, i.e. momentum equations solver works!

Best regards,

Kai

### CODE REVIEW

**Comment by simulkade** [comment]
This is very exciting :100: . I just merged it, but I have not tested it yet. I'm going to do it right now :-)

**Comment by simulkade** [comment]
Wow! It works great. Very well done.

**Comment by KaiSchu** [comment]
Thanks! It think convergence of solving the momentum equations could be heavily increased by using a higher order scheme o the power law scheme for the convection term instead of the upwind scheme, but I wasn't able to correctly implement it... maybe you could have a look at some day

**Comment by simulkade** [comment]
I have already implemented a TVD scheme which is a bit quick and dirty. It should not be difficult to implement the QUICK and other standard higher order schemes. I think we can re-design the Mesh, Cell and Face Variable objects to make them more general (without making them too complicated), especially the ghost cells and boundary conditions.
There must be a smart way to have easy and separate access to internal and ghost cells. Then everything will be much simpler.

**Pull request merged**
